### ISSUE TITLE
How to set the text/voice mode？

### ISSUE THREAD

**Issue by hllGitHub** [Sensely/SDK-iOS#1]
I want to expand more functions, for example, text or voice mode switching, how to set it?
And I want to use the 'SNAssessment' class, but 'create:(nonnull NSString *)jsonString;' that I don't know what the jsonString is. Thank you! I hope you can help me.

**Comment by GRyabkin** [comment]
Hi, sorry we don't have support to switch between voice and text mode for now.

**Comment by GRyabkin** [comment]
Do you want to inject your own conversation?

**Comment by hllGitHub** [comment]
Yes.We want to customize our own UI and do some functional extensions.I have one more question. Install the SDK by cocoapods and find the latest versions are out of use.

**Comment by GRyabkin** [comment]
Currently, x86_64 architecture isn't supported. Please try to update sample app. SNAssessment class isn't available for usage. Could you please reach us by email to negotiate what exactly you want to extend.

**Comment by hllGitHub** [comment]
We want to embed Avatar and add our own navigation bar. When update the sample app, we found that sensely did not support iOS 9.0 through cocoapods installation. The README says 8.0 is supported.

**Comment by bdan010** [comment]
This issue is in the wrong repo, so I am going to delete it.
