### ISSUE TITLE
Voice recognition does not seem to work properly.

### ISSUE THREAD

**Issue by hllGitHub** [Sensely/SDK-iOS#3]
We used the latest 1.2.4 SDK and found that speech recognition does not seem to work. Is it because we use Demo? 
At the same time, we also hope that similar functions like SenselyApp can switch VoiceChat and TextChat to prevent the user's speech recognition from working properly. Before you have told me that you don't provide such a function for the time being, I still hope we can have a better way to serve the user. Thank you!

Equipment model
> iPhone5s     iOS10.0.2

![img_3357](https://user-images.githubusercontent.com/15081858/41076426-2452e916-6a44-11e8-89e1-8560be799aa5.JPG)
![img_3358](https://user-images.githubusercontent.com/15081858/41076427-2481a90e-6a44-11e8-93c4-9c4019fa13ed.JPG)
![img_3359](https://user-images.githubusercontent.com/15081858/41076428-24b16d42-6a44-11e8-8609-1dca672104ee.JPG)

**Comment by GRyabkin** [comment]
What language is set for "voiceRecLangID" param in SenselyConfiguration?
Here is a list of supported Chinesse languages:
"cmn-Hans-HK"
"cmn-Hant-TW"
"yue-Hant-HK"
"cmn-Hans-HK"
"cmn-Hans-CN"

**Comment by GRyabkin** [comment]
Right now SDK has only Voice mode.

**Comment by bdan010** [comment]
This issue is in the wrong repo, so I am going to delete it.
