### ISSUE TITLE
 Questions about running DemoAssessment "Test Mayo Symptom Triage for Carevoice"

### ISSUE THREAD

**Issue by hllGitHub** [Sensely/SDK-iOS#4]
Hello, 
when we trying to run the “Test Mayo Symptom Triangle for CareVoice” assessment there appeared some problems:
1.There’s a “My Full Assessment”  conclusion which may lead into a webpage, but there’s no “back” button for us to go back to the sensely conversation, hence there’s no json data generated. We compared the iOS 1.2.4 SDK with the official Sensely app, the difference is as the following:
![img_0184](https://user-images.githubusercontent.com/15081858/41712079-3f5b323e-757c-11e8-8e01-67107669d803.PNG)
![img_5360](https://user-images.githubusercontent.com/15081858/41712080-3f9dbab4-757c-11e8-9bc1-d7324c19a97e.PNG)

2.Another problem is that in the diagnosis process there is a “Emergency indicators” (Which may occur by this procedure: `Please choose the closest category. (choose ‘Genital/rectal/urinary’) -> Please choose one of these. (choose ‘Urinary problems’) -> Emergenct indicators`), in clicking following choices the Demo will crash, following is the log file:
![sensely_crash](https://user-images.githubusercontent.com/15081858/41712179-804194be-757c-11e8-84d0-c91e615cf2f0.png)

And also, you’ve provided  a file  [Sensely_CareVoice_Specialist_Mappint.xlsx](https://github.com/Sensely/The-CareVoice/files/2121442/Sensely_Carevoice_Specialist_Mapping.xlsx) for us as reference, but we can not find the string of “asset_id” in the json data we captured. What we can fetch is as the following:
<img width="613" alt="sensely_json" src="https://user-images.githubusercontent.com/15081858/41712130-5c8d374e-757c-11e8-88bb-41c1fc164a42.png">

<img width="684" alt="sensely_mappint" src="https://user-images.githubusercontent.com/15081858/41712157-71b0e47c-757c-11e8-8cc3-cf2df415685e.png">

Hope we could have your help with these problems, thanks!

[SenselySDKSample.crash.zip](https://github.com/Sensely/SDK-iOS/files/2123060/SenselySDKSample.crash.zip)

**Comment by GRyabkin** [comment]
Hi Jeffry, nice findings. I have pushed an SDK updated where those problems are fixed. Please pull the latest sample version and run pod install (the latest SDK version now is 1.2.5). Thanks

**Comment by hllGitHub** [comment]
Thank you! I have already pull the latest sample version and run pod install. 
But there seems to be some problems here. One problem is that the new SDK has modified the error's enumeration. There is no synchronization modification in the demo. Another problem is that after updating the SDK, the Avatar system does not seem to work well. At most, only two conversations have been executed. Many of them have been in the first conversation and are waiting. I tested Sensely's official App with the same account and network, and it is normal.

**Comment by GRyabkin** [comment]
Hi Jeffrey, I know about slow response problem. We are investigating it now. I will let you know when we fix it. Please feel free to create a separate issue. Thanks.

**Comment by bdan010** [comment]
This issue is in the wrong repo, so I am going to delete it. It's closed, so it was resolved.
